apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: star-cpcc-net
  namespace: default
spec:
  secretName: star-cpcc-net
  duration: 8760h
  issuerRef:
    name: cpcc-net-issuer
    kind: ClusterIssuer
  commonName: cpcc.net
  dnsNames:
    - "*.cpcc.net"